project:
  type: website

website:
  title: "Allen Hernandez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Project.qmd 
        text: Project 
      - href: Personal.qmd
        text: Personal
    
    

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

